[package]
name = "mcserver-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "4.3.6"
openssl = "0.10.52"
openssl-sys = "0.9.87"
serde = { version = "1.0.161", features=["derive"] }
serde_json = "1.0.96"
toml = "0.7.3"
